Add Math operations
Allatest/AQA-JavaScript-Advanced pull request #4
Opened 2023-09-27 20:21 UTC by Allatest

2023-09-29 16:06 UTC, landriiuk requested changes

2023-09-29 16:06 UTC, landriiuk commented on js-operators-coercion/operators.js
> +
Why is this code commented on?

2023-09-29 16:06 UTC, landriiuk commented on js-operators-coercion/string.js
missed verification " - перевірте чи містить дана строка слово "world""

2023-09-29 16:06 UTC, landriiuk commented on js-operators-coercion/number.js
> +myNumber = Math.round(myNumber * 10) / 10;
you can use toFixed(1);

2023-09-29 16:08 UTC, landriiuk commented
There are a few moments that need to be finished or reworked. Pls finish and fix, then merge this pr

2023-10-12 13:12 UTC, Allatest reviewed
New changes added

2023-10-12 13:12 UTC, merged